import * as THREE from 'three';
import { OrbitControls } from './vendor/OrbitControls.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let report, iteration=1, artifactBase='artifacts/demo/', currentGroup='all', translucent=true, exploded=false, runner='', token='', execution='deterministic', jobBusy=false;
let scene, camera, renderer, controls, assembly, renderRunning=false;
let gridHelper=null, ringMesh=null, selectedName=null, isolatedName=null, deploy=false, deployEnv='studio';
const DESIGNS_KEY='autocadent.designs', DEMO_SPEC={length:0,width:0,mast_height:0};
let model='rove1';
let pendingMeshes=null;
function setViewStatus(msg,mode){const el=document.getElementById('view-status');if(!el)return;el.textContent=msg||'';el.hidden=!msg;el.dataset.mode=mode||'info';window.__viewStatus=msg||''}
function tick(){if(!renderer)return;if(hoverEvt&&!$('#preview-view').hidden){const e=hoverEvt;hoverEvt=null;try{hoverTip(pickAt(e.clientX,e.clientY),e.clientX,e.clientY)}catch{}}controls.update();renderer.render(scene,camera);updateScale()}
function startRender(){if(!renderer||renderRunning)return;renderRunning=true;renderer.setAnimationLoop(tick)}
function stopRender(){if(!renderer)return;renderRunning=false;renderer.setAnimationLoop(null)}
// ---- boot intro (loading sequence; purely decorative, uses real recorded values for init lines) ----
const boot=document.getElementById('boot');
let bootDone=false,booting=false;
let reportReadyResolve;const reportReady=new Promise(r=>reportReadyResolve=r);
function finishBoot(){if(!boot||bootDone)return;bootDone=true;booting=false;document.querySelectorAll('body>*:not(#boot)').forEach(n=>n.removeAttribute('inert'));boot.style.transition='opacity .5s ease';boot.style.opacity='0';setTimeout(()=>boot.remove(),520)}
async function realBootLines(){const r=await Promise.race([reportReady,new Promise(s=>setTimeout(()=>s(null),1000))]);
 const manifest='report.json · benchmark.json · board/drc.json · board/nets.json';
 if(!r)return[`geometry cache ........ unavailable`,`recorded build ........ —`,manifest,`revision status ....... build artifacts missing`,`workspace ............. recorded view only`];
 const last=r.iterations.at(-1),ev=last.evaluation,pass=ev.checks.filter(c=>c.passed).length,total=ev.checks.length;
 return[`geometry cache ........ ${ev.checks[0].measured} valid solids`,`recorded build ........ ${r.seconds}s kernel workflow · ${r.iterations.length} iteration${r.iterations.length>1?'s':''}`,manifest,`revision status ....... REV ${String(r.final_iteration).padStart(2,'0')} · ${r.passed?'EVALUATED · PASS':'NEEDS REVIEW'} · ${pass}/${total} checks`,`workspace ............. dashboard ready`]}
if(boot){if(matchMedia('(prefers-reduced-motion: reduce)').matches){boot.remove()}else{booting=true;document.querySelectorAll('body>*:not(#boot)').forEach(n=>n.setAttribute('inert',''));const guard=setTimeout(finishBoot,3400);boot.addEventListener('click',finishBoot);window.addEventListener('keydown',e=>{if(!bootDone&&['Enter','Space','Escape'].includes(e.code)&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))finishBoot()});setTimeout(async()=>{if(bootDone)return;boot.dataset.phase='term';const lines=await realBootLines();boot.querySelector('.boot-term-lines').innerHTML='';lines.forEach((t,i)=>{const d=document.createElement('div');d.className='boot-line';d.innerHTML=`<span>${t}</span><i></i>`;boot.querySelector('.boot-term-lines').appendChild(d);setTimeout(()=>{if(!bootDone)d.classList.add('on')},i*140)});setTimeout(finishBoot,300+lines.length*140+120)},1400)}}
const toast=s=>{ $('#toast').textContent=s; $('#toast').classList.add('show'); setTimeout(()=>$('#toast').classList.remove('show'),4000); };
async function json(url,options){const r=await fetch(url,options); if(!r.ok){let detail;try{detail=(await r.json()).detail}catch{}throw Error(detail?JSON.stringify(detail):`Request failed (${r.status})`)}return r.json()}
function modal(title,html){$('#modal-content').innerHTML=`<h2>${title}</h2>${html}`; if(!$('#modal').open)$('#modal').showModal()}
$('#close-modal').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close()};
function init3D(){
 scene=new THREE.Scene(); camera=new THREE.PerspectiveCamera(33,1,.1,3000); camera.up.set(0,0,1);
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;
 $('#viewport').appendChild(renderer.domElement); controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=150;controls.maxDistance=850;controls.maxPolarAngle=Math.PI*.85;
 scene.add(new THREE.HemisphereLight(0xfff9e8,0x596c65,2.4)); const sun=new THREE.DirectionalLight(0xfff7e4,3.5);sun.position.set(150,-180,260);scene.add(sun);const fill=new THREE.DirectionalLight(0x8ac0bb,1.2);fill.position.set(-100,150,60);scene.add(fill);
 const grid=new THREE.GridHelper(550,22,0xb8b7a3,0xd4d2bf);grid.rotation.x=Math.PI/2;grid.position.z=-25;grid.material.transparent=true;grid.material.opacity=.4;scene.add(grid);gridHelper=grid;
 const ring=new THREE.Mesh(new THREE.RingGeometry(119,119.35,100),new THREE.MeshBasicMaterial({color:0xa5b2a1,transparent:true,opacity:.5,side:THREE.DoubleSide}));ring.position.z=-24.8;scene.add(ring);ringMesh=ring;
 new ResizeObserver(()=>{let w=$('#viewport').clientWidth,h=$('#viewport').clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}).observe($('#viewport'));
 reset();
 renderer.domElement.addEventListener('pointermove',e=>{hoverEvt=e});
 renderer.domElement.addEventListener('pointerdown',e=>{downPos=[e.clientX,e.clientY]});
 renderer.domElement.addEventListener('pointerup',e=>{if(!downPos)return;const dx=e.clientX-downPos[0],dy=e.clientY-downPos[1];downPos=null;if(dx*dx+dy*dy>36)return;const hit=pickAt(e.clientX,e.clientY);selectPart(hit?hit.userData.name:null)});
 renderer.domElement.addEventListener('pointerleave',()=>{hoverEvt=null;hoverTip(null)});
 if(!$('#preview-view').hidden)startRender();if(pendingMeshes){drawMeshes(pendingMeshes);pendingMeshes=null}else setViewStatus('Loading recorded geometry…','loading');
}
function reset(){if(!camera)return;camera.position.set(265,-330,225);controls.target.set(0,0,20);controls.update()}
const raycaster=new THREE.Raycaster(), pointerNDC=new THREE.Vector2();
let hoverEvt=null, downPos=null;
function visibleMeshes(){return assembly?assembly.children.filter(m=>m.isMesh&&m.visible):[]}
function pickAt(cx,cy){if(!renderer||!assembly)return null;const r=renderer.domElement.getBoundingClientRect();pointerNDC.set(((cx-r.left)/r.width)*2-1,-((cy-r.top)/r.height)*2+1);raycaster.setFromCamera(pointerNDC,camera);const hits=raycaster.intersectObjects(visibleMeshes(),false);return hits.length?hits[0].object:null}
function hoverTip(mesh,cx,cy){const tip=$('#part-tip');if(!tip)return;if(!mesh){tip.hidden=true;if(renderer)renderer.domElement.style.cursor='';return}const u=mesh.userData;tip.innerHTML=`<b>${escape(u.name||'Part')}</b><small>${escape(u.group||'')}</small>`;tip.hidden=false;const wrap=$('#preview-view').getBoundingClientRect();tip.style.left=(cx-wrap.left)+'px';tip.style.top=(cy-wrap.top)+'px';renderer.domElement.style.cursor='pointer'}
function selectPart(name){selectedName=name;if(assembly)assembly.children.forEach(m=>{if(m.material&&m.material.emissive){const on=m.userData.name===name;m.material.emissive.setHex(on?0x2b7770:0x000000);m.material.emissiveIntensity=on?.38:0}});renderAssemblyPanel();renderTimeline()}
function partSize(mesh){try{const b=new THREE.Box3().setFromObject(mesh),s=b.getSize(new THREE.Vector3());return `${s.x.toFixed(1)} × ${s.y.toFixed(1)} × ${s.z.toFixed(1)} mm`}catch{return '—'}}
function renderAssemblyPanel(){const sum=$('#assembly-summary'),det=$('#part-details');if(!sum||!det)return;const kids=assembly?assembly.children.filter(m=>m.isMesh):[];if(!selectedName){det.hidden=true;sum.hidden=false;if(!kids.length){sum.innerHTML='<p class="field-hint">Loading geometry…</p>';return}const groups={};let tris=0;kids.forEach(m=>{const g=m.userData.group||'part';groups[g]=(groups[g]||0)+1;const ix=m.geometry.getIndex();tris+=ix?ix.count/3:m.geometry.getAttribute('position').count/3});sum.innerHTML=`<div class="stat-grid"><div class="stat"><b>${kids.length}</b>parts</div><div class="stat"><b>${Math.round(tris).toLocaleString('en-US')}</b>triangles</div></div>`+Object.entries(groups).map(([g,n])=>`<div class="constraint"><span style="text-transform:capitalize">${escape(g)}</span><b>${n}</b></div>`).join('')+`<p class="field-hint">Hover the model for names. Click a part for measurements.</p>`;return}const mesh=kids.find(m=>m.userData.name===selectedName);if(!mesh){selectedName=null;renderAssemblyPanel();renderTimeline();return}const u=mesh.userData;let tris=0;try{const ix=mesh.geometry.getIndex();tris=Math.round(ix?ix.count/3:mesh.geometry.getAttribute('position').count/3)}catch{}const col=mesh.material.color?mesh.material.color.getStyle():'#999999';sum.hidden=true;det.hidden=false;det.innerHTML=`<div class="part-detail-head"><span class="swatch" style="background:${escape(col)}"></span><h4>${escape(u.name||'Part')}</h4></div><div class="kv"><span>Group</span><b style="text-transform:capitalize">${escape(u.group||'—')}</b></div><div class="kv"><span>Bounding box</span><b>${partSize(mesh)}</b></div><div class="kv"><span>Triangles</span><b>${tris.toLocaleString('en-US')}</b></div><div class="kv"><span>Printable</span><b>${u.printable?'via pipeline':'reference only'}</b></div><div class="dash-actions"><button class="text-button" data-pact="isolate">${isolatedName?'Show all':'Isolate part'}</button><button class="text-button" data-pact="back">← All parts</button></div>`}
function renderTimeline(){const host=$('#timeline-chips'),count=$('#timeline-count');if(!host)return;const kids=assembly?assembly.children.filter(m=>m.isMesh):[];if(count)count.textContent=kids.length?`${kids.length} parts`:'—';host.innerHTML=kids.map(m=>{const u=m.userData;const col=m.material.color?m.material.color.getStyle():'#999999';return `<button class="chip${u.name===selectedName?' active':''}" data-chip="${escape(u.name||'')}" title="${escape(u.name||'Part')}"><i style="background:${escape(col)}"></i><span>${escape(u.name||'Part')}</span><small>${escape(u.group||'')}</small></button>`}).join('')}
let lastScale='';
function updateScale(){
 if(!camera||!renderer)return;const vw=$('#viewport'),bar=$('#scale-bar');if(!vw||!bar||!vw.clientWidth)return;
 const halfW=vw.clientWidth/2,halfH=vw.clientHeight/2,plane=new THREE.Plane(new THREE.Vector3(0,0,1),25);
 const hit=(x,y)=>{const ndc=new THREE.Vector2(x/halfW-1,-(y/halfH-1));const r=new THREE.Raycaster();r.setFromCamera(ndc,camera);const p=new THREE.Vector3();return r.ray.intersectPlane(plane,p)?p:null};
 const a=hit(halfW,halfH),b=hit(halfW+140,halfH);if(!a||!b)return;const dist=a.distanceTo(b);if(dist<1e-6)return;
 const nice=[500,200,100,50,20,10];const m=nice.find(v=>v<=dist)||10;const key=`${m} mm ${(140*m/dist).toFixed(0)}`;
 if(key===lastScale)return;lastScale=key;bar.style.width=(140*m/dist).toFixed(0)+'px';$('#scale-label').textContent=`${m} mm`;
}
function drawMeshes(meshes){
 if(!scene){pendingMeshes=meshes;return}
 if(assembly){assembly.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose()});scene.remove(assembly)}
 assembly=new THREE.Group();
 for(const p of meshes){try{
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(p.vertices.flat(),3));geometry.setIndex(p.triangles.flat());geometry.computeVertexNormals();
  const op=p.opaque===true;const material=new THREE.MeshStandardMaterial({color:p.color,roughness:op?.5:.58,metalness:op?.28:.12,transparent:!op,opacity:op?1:(translucent?.58:1),side:THREE.DoubleSide,depthWrite:op?true:!translucent});
  const mesh=new THREE.Mesh(geometry,material);mesh.userData=p;const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geometry,25),new THREE.LineBasicMaterial({color:p.group==='electronics'?0x286f70:0x536059,transparent:true,opacity:.5}));if(p.edges!==false)mesh.add(edges);assembly.add(mesh)
 }catch(e){console.warn('Skipping a non-renderable part:',p?.name,e)}}
  scene.add(assembly);
  selectedName=null;isolatedName=null;if(typeof hoverTip==='function')hoverTip(null);
  updateModel();renderAssemblyPanel();renderTimeline();setViewStatus('','');
}
function fitAssembly(){if(!assembly||!camera)return;const box=new THREE.Box3().setFromObject(assembly);const c=box.getCenter(new THREE.Vector3()),s=box.getSize(new THREE.Vector3());const maxDim=Math.max(s.x,s.y,s.z)||1;const dist=maxDim/(2*Math.tan(camera.fov*Math.PI/360))*1.35;const dir=camera.position.clone().sub(controls.target);if(!dir.lengthSq())dir.set(1,-1,.7);dir.normalize();controls.target.copy(c);camera.position.copy(c.clone().add(dir.multiplyScalar(dist)));camera.near=Math.max(.1,dist/100);camera.far=dist*20;camera.updateProjectionMatrix();controls.update()}
function updateModel(){if(!assembly)return;assembly.children.forEach((mesh,i)=>{mesh.visible=isolatedName?mesh.userData.name===isolatedName:(currentGroup==='all'||mesh.userData.group===currentGroup);mesh.material.opacity=mesh.userData.opaque?1:(translucent?.56:1);mesh.material.depthWrite=mesh.userData.opaque?true:!translucent;mesh.position.z=exploded?(mesh.userData.group==='electronics'?48:mesh.userData.name==='Sensor mast'?30:mesh.userData.name==='Board tray'?20:0):0; if(mesh.userData.group==='mobility')mesh.position.y=exploded?(i%4<2?-22:22):0;});}
$$('[data-group]').forEach(b=>b.onclick=()=>{currentGroup=b.dataset.group;$$('[data-group]').forEach(el=>el.classList.toggle('active',el===b));updateModel()});
$('#reset-view').onclick=reset;$('#wireframe').onclick=()=>{translucent=!translucent;$('#wireframe').setAttribute('aria-pressed',translucent);updateModel()};$('#explode').onclick=()=>{exploded=!exploded;$('#explode').setAttribute('aria-pressed',exploded);updateModel()};
function zoom(f){camera.position.sub(controls.target).multiplyScalar(f).add(controls.target);controls.update()};$('#zoom-in').onclick=()=>zoom(.85);$('#zoom-out').onclick=()=>zoom(1.15);
function tab(name){const views={dashboard:'dashboard',preview:'preview',explorer:'preview',files:'files',designs:'designs',schematic:'schematic',layout:'layout'};const key=views[name]||'dashboard';const tabKey=key==='dashboard'?null:key;$$('[data-tab]').forEach(b=>{const on=b.dataset.tab===tabKey;b.classList.toggle('active',!!on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});['dashboard','preview','files','designs','schematic','layout'].forEach(n=>$(`#${n}-view`).hidden=n!==key);document.body.classList.toggle('is-landing',key==='dashboard');const back=$('#back-dashboard');if(back)back.hidden=key==='dashboard';if(key==='preview'){window.dispatchEvent(new Event('resize'));startRender()}else stopRender();const names={dashboard:'Dashboard',preview:'Explorer',files:'Files',designs:'Designs',schematic:'Schematic',layout:'Layout'};const crumb=$('#view-crumb');if(crumb)crumb.textContent=names[key];if(key==='designs')renderDesigns();const want='#/'+(key==='preview'?'explorer':key);if(location.hash!==want)history.replaceState(null,'',want);}
$$('[data-tab]').forEach(b=>b.onclick=()=>{location.hash='#/'+(b.dataset.tab==='preview'?'explorer':b.dataset.tab)});window.addEventListener('hashchange',()=>{const h=(location.hash||'').replace(/^#\/?/,'');tab(h||'dashboard')});
function pulseHero(){const h=document.querySelector('.canvas-title');if(!h)return;h.classList.remove('intro-hide');clearTimeout(window.__heroT);window.__heroT=setTimeout(()=>h.classList.add('intro-hide'),4500)}
function syncModelButtons(){$$('[data-model]').forEach(b=>{const on=b.dataset.model===model;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))})}
async function loadOrionMeshes(){const man=await json('artifacts/orion/mesh.json');const res=await fetch('artifacts/orion/mesh.bin');if(!res.ok)throw Error('bundle missing');const buf=await res.arrayBuffer();const F=new Float32Array(buf,0,man.vertTotal*3),I=new Uint32Array(buf,man.vertTotal*12);return man.parts.map(p=>({name:p.name,color:p.color,group:p.group,printable:p.printable,edges:p.edges,opaque:p.opaque,vertices:Array.from(F.subarray(p.vertStart,p.vertStart+p.vertCount*3)),triangles:Array.from(I.subarray(p.triStart,p.triStart+p.triCount*3))}))}
async function loadModel(name){
 model=name;syncModelButtons();
 if(name==='orion'){
  setViewStatus('Loading reference geometry…','loading');
  try{
   drawMeshes(await loadOrionMeshes());
   $('#brief-text').textContent='Orion Quadruped by Ashish Agrahari — reference geometry (16 parts, zero-pose URDF assembly). Unevaluated; not measured.';
   $('#revision-label').textContent='ORION · REFERENCE — UNEVALUATED';
   $('#project-state').textContent='Reference geometry';
   $('#run-label').textContent='REFERENCE GEOMETRY';
   $('#replay-btn').hidden=true;
   fitAssembly();
   const cap=$('#geometry-caption');if(cap)cap.textContent='ORION QUADRUPED · REFERENCE STL ASSEMBLY';
  }catch(e){setViewStatus('Reference geometry could not load.','error');toast('Orion geometry unavailable: '+e.message);await loadModel('rove1');return}
 }else{
  $('#replay-btn').hidden=false;
  const cap=$('#geometry-caption');if(cap)cap.textContent='ACTUAL CADQUERY GEOMETRY';
  if(report){syncBriefAndDims();await loadIteration(report.final_iteration)}
 }
 tab('preview');pulseHero();
}
$$('[data-model]').forEach(b=>b.onclick=()=>loadModel(b.dataset.model));
function resizer(id,prop,min,max,dir){const h=document.getElementById(id);if(!h)return;const ws=document.querySelector('.workspace');const base=prop==='--agent-w'?290:259;h.addEventListener('pointerdown',e=>{e.preventDefault();h.setPointerCapture(e.pointerId);h.classList.add('dragging');const startX=e.clientX;const cur=parseFloat(getComputedStyle(ws).getPropertyValue(prop))||base;const move=ev=>{const v=Math.min(max,Math.max(min,cur+(ev.clientX-startX)*dir));ws.style.setProperty(prop,v+'px')};const up=()=>{h.classList.remove('dragging');h.removeEventListener('pointermove',move);h.removeEventListener('pointerup',up)};h.addEventListener('pointermove',move);h.addEventListener('pointerup',up)});h.addEventListener('dblclick',()=>ws.style.removeProperty(prop))}
resizer('resize-agent','--agent-w',200,460,1);resizer('resize-props','--props-w',200,380,-1);
$('#timeline-toggle').onclick=()=>{const tl=$('#parts-timeline');const hide=!tl.classList.contains('collapsed');tl.classList.toggle('collapsed',hide);const b=$('#timeline-toggle');b.textContent=hide?'Show ▸':'Hide ▾';b.setAttribute('aria-expanded',String(!hide))};
$('#timeline-chips').addEventListener('click',e=>{const c=e.target.closest('[data-chip]');if(!c)return;selectPart(selectedName===c.dataset.chip?null:c.dataset.chip)});
$('#assembly-explorer').addEventListener('click',e=>{const b=e.target.closest('[data-pact]');if(!b)return;if(b.dataset.pact==='back'){selectPart(null)}else if(b.dataset.pact==='isolate'){isolatedName=isolatedName?null:selectedName;updateModel();renderAssemblyPanel()}});
function applyDeploy(){const wrap=document.querySelector('.canvas-wrap');if(!wrap)return;wrap.classList.toggle('deploy',deploy);['studio','lab','outdoor','night'].forEach(n=>wrap.classList.toggle('env-'+n,deploy&&deployEnv===n));const pk=$('#env-picker');if(pk)pk.hidden=!deploy;if(gridHelper)gridHelper.visible=!deploy;if(ringMesh)ringMesh.visible=!deploy;if(controls){controls.autoRotate=deploy;controls.autoRotateSpeed=.9}const db=$('#deploy-btn');if(db)db.setAttribute('aria-pressed',String(deploy));if(deploy)toast('Deploy backdrop — visualization only, not a physics sim.')}
$('#deploy-btn').onclick=()=>{deploy=!deploy;applyDeploy()};
$$('#env-picker [data-env]').forEach(b=>b.onclick=()=>{deployEnv=b.dataset.env;$$('#env-picker [data-env]').forEach(x=>x.classList.toggle('active',x===b));applyDeploy()});
const SLASHCMDS=[{c:'/help',d:'List composer commands'},{c:'/goal',d:'Prefix the brief with a goal'},{c:'/spec',d:'Append live dimensions'},{c:'/model',d:'Toggle Rove-1 / Orion example'},{c:'/evidence',d:'Open measured evidence'},{c:'/benchmark',d:'Open repair benchmark'},{c:'/clear',d:'Clear the brief'}];
let slashIdx=0;
function slashMatches(){const ta=$('#brief');const m=ta.value.slice(0,ta.selectionStart).match(/(?:^|\n)\/(\w*)$/);if(!m)return null;return SLASHCMDS.filter(x=>x.c.startsWith('/'+m[1].toLowerCase()))}
function renderSlash(){const menu=$('#slash-menu');const list=slashMatches();if(!list||!list.length){menu.hidden=true;return}slashIdx=Math.min(slashIdx,list.length-1);menu.innerHTML=list.map((x,i)=>`<button data-slash="${i}" class="${i===slashIdx?'active':''}"><b>${x.c}</b><small>${escape(x.d)}</small></button>`).join('');menu.hidden=false;menu.querySelectorAll('[data-slash]').forEach(b=>b.onmousedown=e=>{e.preventDefault();applySlash(list[Number(b.dataset.slash)].c)})}
function applySlash(cmd){const ta=$('#brief');ta.value=ta.value.replace(/(?:^|\n)\/\w*$/,(m)=>m.startsWith('\n')?'\n':'');
 if(cmd==='/help'){modal('Composer commands.',SLASHCMDS.map(x=>`<p><b class="mono">${x.c}</b> — ${escape(x.d)}</p>`).join(''))}
 else if(cmd==='/clear'){ta.value=''}
 else if(cmd==='/spec'){ta.value+=(ta.value&&!ta.value.endsWith('\n')?'\n':'')+`Dimensions: ${$('#length').value||'?'} × ${$('#width').value||'?'} mm, mast ${$('#mast_height').value||'?'} mm.`}
 else if(cmd==='/goal'){ta.value='Goal: '+ta.value}
 else if(cmd==='/model'){loadModel(model==='orion'?'rove1':'orion')}
 else if(cmd==='/evidence'){if(report)showEvidence();else toast('Load the recorded build first.')}
 else if(cmd==='/benchmark'){showBenchmark()}
 ta.focus();$('#slash-menu').hidden=true}
$('#brief').addEventListener('input',()=>{slashIdx=0;renderSlash()});
$('#brief').addEventListener('keydown',e=>{const menu=$('#slash-menu');if(menu.hidden)return;const list=slashMatches()||[];if(e.key==='ArrowDown'){e.preventDefault();slashIdx=(slashIdx+1)%list.length;renderSlash()}else if(e.key==='ArrowUp'){e.preventDefault();slashIdx=(slashIdx-1+list.length)%list.length;renderSlash()}else if(e.key==='Enter'&&list.length){e.preventDefault();applySlash(list[slashIdx].c)}else if(e.key==='Escape'){menu.hidden=true}});
document.addEventListener('click',e=>{const m=$('#slash-menu');if(m&&!m.hidden&&!e.target.closest('#slash-menu')&&e.target.id!=='brief')m.hidden=true});
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){if(a.dataset.action==='new-project')createFromTemplate();return}const v=e.target.closest('[data-evidence]');if(v){if(v.dataset.evidence==='report')showEvidence();else showBenchmark();return}const g=e.target.closest('[data-goto]');if(!g)return;e.preventDefault();location.hash='#/'+(g.dataset.goto==='preview'?'explorer':g.dataset.goto);});
function renderEvidence(){
  const item=report.iterations[iteration-1], last=report.iterations.at(-1);
  const evCls=m=>/fail/i.test(m)?'failure':/pass/i.test(m)?'pass':'';
  $('#activity').innerHTML=(report.events||[]).map((e,i)=>`<div class="event ${evCls(e.message)}" style="animation-delay:${Math.min(i*80,640)}ms"><h3>${escape(e.role)}</h3><p>${escape(e.message)}</p></div>`).join('')||'<div class="event"><h3>No recorded events</h3></div>';
 $('#revision-label').textContent=`REV ${String(iteration).padStart(2,'0')} · ${item.evaluation.passed?'EVALUATED':'CONSTRAINT FAILURE'}`;
 $('#project-state').textContent=report.passed?'Evaluated exemplar':'Needs review';
 $('#replay-btn').textContent=iteration===1&&report.iterations.length>1?'↗ Inspect repaired build':'↺ Inspect initial build';
 $('#run-label').textContent=report.execution==='ao-worker'?'AO WORKER RESULT':runner?'LOCAL KERNEL RESULT':'RECORDED RUN';
 renderFiles();
}
async function loadIteration(n){iteration=n;model='rove1';syncModelButtons();renderEvidence();setViewStatus('Loading geometry…','loading');try{drawMeshes(await json(`${artifactBase}iteration-${iteration}/mesh.json`))}catch(e){setViewStatus('Geometry could not load — check the connection and refresh.','error');toast('Geometry could not load: '+e.message)}}
$('#replay-btn').onclick=()=>loadIteration(iteration===1?report.iterations.length:1);
const extOf=n=>(n.split('.').pop()||'').toUpperCase().slice(0,4)||'FILE';
let boardMeta=null;
async function boardBundleMeta(){if(boardMeta)return boardMeta;try{const r=await fetch('artifacts/board/rove-1-board.zip');if(!r.ok)throw 0;const buf=await r.arrayBuffer();const hex=[...new Uint8Array(await crypto.subtle.digest('SHA-256',buf))].map(b=>b.toString(16).padStart(2,'0')).join('');boardMeta={bytes:buf.byteLength,sha256:hex}}catch{boardMeta={bytes:0,sha256:''}}return boardMeta}
const fmtBytes=n=>n>=1048576?(n/1048576).toFixed(1)+' MB':n>=1024?(n/1024).toFixed(1)+' KB':n+' B';
function fileRows(){const rows=(report?.files||[]).map(f=>`<div class="file-row"><span>${escape(extOf(f.name))}</span><div><b>${escape(f.name)}</b><small>${escape(fmtBytes(f.bytes))} · sha ${escape(String(f.sha256).slice(0,12))}…</small></div><a href="${escape(artifactBase+'final/'+f.name)}" download aria-label="Download ${escape(f.name)}">↓</a></div>`).join('');return rows+`<div class="file-row"><span>PCB</span><div><b>rove-1-board.zip</b><small id="board-zip-meta">KiCad board bundle · resolving…</small></div><a href="artifacts/board/rove-1-board.zip" download aria-label="Download rove-1-board.zip">↓</a></div>`}
function renderFiles(){$('#file-list').innerHTML=fileRows();boardBundleMeta().then(m=>{const el=document.getElementById('board-zip-meta');if(el&&m.bytes)el.textContent=`${fmtBytes(m.bytes)} · sha ${m.sha256.slice(0,12)}…`;else if(el)el.textContent='Board bundle · see download'})}
function syncBriefAndDims(){const last=report.iterations.at(-1);const bt=$('#brief-text');if(bt&&report.description)bt.textContent=report.description;for(const k of ['length','width','mast_height']){const el=document.getElementById(k);if(el&&last.spec[k]!=null)el.value=last.spec[k]}DEMO_SPEC.length=last.spec.length;DEMO_SPEC.width=last.spec.width;DEMO_SPEC.mast_height=last.spec.mast_height;}
function renderDashboard(){
  const last=report.iterations.at(-1), keyChecks=last.evaluation.checks.filter(c=>['Chassis thickness','Tray wall','Board clearance'].includes(c.name));
  const solidCheck=last.evaluation.checks.find(c=>/solid/i.test(c.name));
  const nav=(id,label,note)=>`<button class="dash-nav" data-goto="${id}"><b>${label}</b><span>${escape(note)}</span>↗</button>`;
  $('#dashboard').innerHTML=`<div class="view-heading"><span class="eyebrow">PROJECT DASHBOARD · ${escape(report.project||'ROVE-1')}</span><h2>Rove–1, at a glance.</h2><p>${escape(report.description||'Recorded build.')}</p></div>
  <div class="dash-grid">
    <article class="dash-card"><span class="eyebrow">REVISION STATUS</span><div class="revision-big">REV ${String(report.final_iteration).padStart(2,'0')}</div><div class="revision-state ${report.passed?'':'fail'}">${report.passed?'EVALUATED · PASS':'NEEDS REVIEW'}</div><p>${report.iterations.length} iteration${report.iterations.length>1?'s':''} · ${report.seconds}s kernel workflow</p><p class="muted">${report.passed?'All scoped dimensional checks pass on the repaired build.':'One or more scoped checks still fail on the final revision.'}</p></article>
    <article class="dash-card"><span class="eyebrow">CHECKS SUMMARY</span>${keyChecks.map(c=>`<div class="dash-check ${c.passed?'':'fail'}"><span>${escape(c.name)}</span><b>${c.measured.toFixed(1)} <small>mm</small></b><em>${c.passed?'PASS':'FAIL'}</em></div>`).join('')}<p class="muted">${solidCheck?escape(String(solidCheck.measured))+' '+escape(solidCheck.unit||'solids'):''} · measured on solid geometry, not a print or stress test.</p><div class="dash-actions"><button class="text-button" data-evidence="report">View evidence ↗</button><button class="text-button" data-evidence="benchmark">Benchmark ↗</button></div></article>
    <article class="dash-card"><span class="eyebrow">REPAIR BENCHMARK</span><div class="bench-big" id="bench-figure">…</div><p class="muted" id="bench-note">Loading regression corpus…</p></article>
    <article class="dash-card"><span class="eyebrow">REVISIONS</span>${report.iterations.map(it=>{const ev=it.evaluation,ok=ev.checks.filter(c=>c.passed).length;return `<div class="rev-row ${ev.passed?'':'fail'}"><span class="mono">REV ${String(it.iteration).padStart(2,'0')}</span><span>${it.spec.length} × ${it.spec.width} mm · t ${it.spec.thickness} / w ${it.spec.wall} / c ${it.spec.clearance}<small>${ok}/${ev.checks.length} checks · ${ev.passed?'accepted':'failed'}</small></span><em>${ev.passed?'PASS':'FAIL'}</em></div>`}).join('')}<p class="muted">Session ${escape(report.ao_session||'—')} · ${escape(report.execution||'')} run.</p></article>
    <article class="dash-card"><span class="eyebrow">PROJECTS</span><div class="rev-row"><span class="mono">ROVE–1</span><span>Recorded example · ${report.iterations.length} revisions<small>${escape(report.description||'')}</small></span><em>${report.passed?'PASS':'FAIL'}</em></div><div class="rev-row"><span class="mono">MINE</span><span id="dash-designs-note">Loading browser library…</span></div><div class="rev-row"><span class="mono">REF</span><span>Orion Quadruped<small>External quadruped build — load it in the Explorer via the Orion switch. Reference only, not evaluated.</small></span><a class="text-button" href="https://github.com/AshishA26/Orion-Quadruped" target="_blank" rel="noreferrer">Open ↗</a></div><div class="dash-actions"><button class="text-button" data-action="new-project">＋ New project</button><button class="text-button" data-goto="designs">Open designs ↗</button></div></article>
  </div>
  <div class="dash-links">${nav('preview','Assembly explorer','orbit · isolate · explode')}${nav('files','Build outputs','STEP · STL · ZIP · source + hashes')}${nav('schematic','Connectivity diagram','four nets · J1 ↔ J2')}${nav('layout','Board layout','KiCad export · DRC evidence')}</div>`;
  try{const mine=loadDesigns();const el=document.getElementById('dash-designs-note');if(el)el.textContent=mine.length?mine.length+' saved in this browser — open via Designs.' :'No saved designs yet — create one in Designs.'}catch{}
  json('artifacts/benchmark.json').then(b=>{$('#bench-figure').innerHTML=`<b>${b.after_pass_count}</b>/${b.case_count}<span>pass after repair</span>`;$('#bench-note').textContent=`${b.before_pass_count} of ${b.case_count} initially accepted; deterministic repair recovers ${b.after_pass_count-b.before_pass_count}. Fixed regression corpus, not an LLM benchmark.`}).catch(()=>{$('#bench-figure').textContent='—';$('#bench-note').textContent='Benchmark artifact unavailable.'});
};$('#export-btn').onclick=()=>modal('Take the build with you.',`<p>Final evaluated CAD plus a fixed connector-board exemplar. Sensor and wheel envelopes are included in STEP for assembly context, not as printable hardware.</p>${fileRows()}`);
function showEvidence(){const ev=report.iterations[iteration-1].evaluation;modal(`Revision ${iteration}: the evidence.`,`<p>Measured by OpenCASCADE. Solid validity is separate from dimensional acceptance. These checks do not certify strength, electrical safety, or printability.</p><table><thead><tr><th>Check</th><th>Measured</th><th>Requirement</th><th>Result</th></tr></thead><tbody>${ev.checks.map(c=>`<tr><td title="${escape(c.method)}">${c.name}</td><td>${c.measured} ${c.unit}</td><td>${escape(c.requirement)}</td><td>${c.passed?'PASS':'FAIL'}</td></tr>`).join('')}</tbody></table><p>Tray wall: paired planar side-face offsets. Board gap: minimum solid distance to tray sidewalls. No global wall analysis or structural simulation.</p><a class="download-link" href="${artifactBase}report.json" download>Download complete report ↗</a>`)};
async function showBenchmark(){try{const b=await json('artifacts/benchmark.json');modal('Small corpus. Real measurements.',`<p>${escape(b.kind)}. Each case builds real solids, evaluates, applies a fixed repair policy, then evaluates again.</p><table><thead><tr><th>Case</th><th>Initial</th><th>After repair</th></tr></thead><tbody>${b.cases.map(c=>`<tr><td>${c.case}</td><td>${c.before.passed?'PASS':'FAIL'}</td><td>${c.after.passed?'PASS':'FAIL'}</td></tr>`).join('')}</tbody></table><p>${b.before_pass_count} of ${b.case_count} initially accepted; ${b.after_pass_count} of ${b.case_count} after repair. This is a fixed regression corpus, not a general agent benchmark.</p><a class="download-link" href="artifacts/benchmark.json" download>Download benchmark artifact ↗</a>`)}catch(e){toast(e.message)}};
$('#guide-btn').onclick=()=>modal('An open engineering notebook.',`<p>AutoCadent turns a bounded robot brief into geometry you can inspect, evaluate and take with you.</p><h3>01 / Inspect the assembly</h3><p>Orbit the actual tessellated CAD model. Isolate the chassis, board or wheels. Toggle X-ray or explode the assembly.</p><h3>02 / Follow the correction</h3><p>Inspect the initial build: valid solids with failed thickness, wall and clearance constraints. Switch to the repaired build and open its measurements.</p><h3>03 / Build your variation</h3><p>Start the local runner, connect, edit the dimensions and submit your brief. The deterministic mode uses explicit dimensions; your prose is preserved as design intent. AO mode dispatches a real AO worker with the same bounded template.</p><pre>uv sync --python 3.12\nuv run uvicorn autocadent.api:app --host 127.0.0.1 --port 8766\n# Open http://127.0.0.1:8766</pre><p>GitHub Pages serves recorded artifacts. It cannot run CAD or agents. The signal board is a fixed exemplar, not a motor controller. The rover is an educational assembly, not validated hardware.</p><a class="download-link" target="_blank" rel="noreferrer" href="https://github.com/Anthony-Sin/AutoCadent-SyndicatebyMaximor">Setup, architecture & demo guide ↗</a>`);
$('#mcp-btn').onclick=async()=>{try{const e=await json('artifacts/mcp-status.json');modal('Tools, actually connected.',`<p>MCP initialize, tools/list and useful-call evidence from the local toolchain. These are recorded verification results, not a current connection to your machine.</p><table><tr><th>Server</th><th>Tools</th><th>Verified call</th></tr>${e.servers.map(s=>`<tr><td>${escape(s.name)}</td><td>${s.tools}</td><td>${escape(s.call)} · ${s.passed?'PASS':'FAIL'}</td></tr>`).join('')}</table><p>KiCad uses the pinned BCI-style uvx setup. AutoCadent CAD is a project-specific MCP server for bounded CadQuery generation and measurement.</p><a class="download-link" href="artifacts/mcp-status.json" download>Download verification summary ↗</a>`)}catch(e){toast(e.message)}};
function connectDialog(){modal('Bring your own runner.',`<p>Pages is a recorded artifact explorer. Start the runner locally and open its address for live CAD. Connecting from Pages requires an explicitly allowed origin. Use an authenticated HTTPS runner for remote hosting.</p><label for="runner-url">Runner URL</label><input id="runner-url" type="url" value="${escape(runner||'http://127.0.0.1:8766')}" placeholder="http://127.0.0.1:8766"><label for="runner-token">Runner token (only if configured; kept in memory)</label><input id="runner-token" type="password" autocomplete="off"><label for="execution-mode">Execution mode</label><select id="execution-mode"><option value="deterministic">Local CAD kernel + deterministic repair policy</option><option value="ao">Supervisor → actual AO worker → evaluator</option></select><button id="do-connect" class="dark-button">Connect runner ↗</button><p id="connect-status" role="status"></p>`);$('#execution-mode').value=execution;$('#do-connect').onclick=async()=>{const raw=$('#runner-url').value;try{const url=new URL(raw);if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.search||url.hash)throw Error('Use an HTTP(S) runner origin without credentials or query parameters.'); const next=url.origin; const nextToken=$('#runner-token').value; const mode=$('#execution-mode').value;const h=await json(next+'/api/health',{headers:nextToken?{Authorization:'Bearer '+nextToken}:{}});if(mode==='ao'&&!h.ao_enabled)throw Error('AO dispatch is disabled on this runner. Enable AUTOCADENT_ENABLE_AO=1 server-side.');runner=next;token=nextToken;execution=mode;$('#connection-label').textContent=mode==='ao'?'AO runner connected':'Local runner connected';$('#composer-mode').textContent=mode==='ao'?'AO WORKER DISPATCH':'LOCAL CAD KERNEL';$('#footer-mode').textContent=mode==='ao'?'RUNNER CONNECTED · AO JOBS ON REQUEST':'RUNNER CONNECTED · DETERMINISTIC CAD';$('#modal').close();toast('Runner connected. Edit dimensions and submit your brief.')}catch(e){$('#connect-status').textContent=e.message}};}
$('#connect-btn').onclick=connectDialog;
$('#brief-form').onsubmit=async e=>{e.preventDefault();if(jobBusy)return;if(!runner){$('#brief-feedback').textContent='Connect a local runner to generate your design. The recorded build is ready to inspect and download.';connectDialog();return}const description=$('#brief').value.trim();if(!description){$('#brief-feedback').textContent='Add a short description of your rover.';return}const spec={};for(const name of ['length','width','mast_height']){const input=$('#'+name);if(!input.checkValidity()){input.reportValidity();return}spec[name]=Number(input.value)}jobBusy=true;$('#submit-brief').disabled=true;$('#brief-feedback').textContent=execution==='ao'?'Supervisor dispatching an actual AO worker…':'Building and evaluating real CAD geometry…';const headers={'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};try{const created=await json(runner+'/api/jobs',{method:'POST',headers,body:JSON.stringify({description,spec,execution})});let job;const deadline=Date.now()+15*60*1000;while(Date.now()<deadline){job=await json(runner+'/api/jobs/'+created.id,{headers});if(job.status==='complete'||job.status==='failed')break;$('#brief-feedback').textContent=job.message||'CAD worker running…';await new Promise(r=>setTimeout(r,2000))}if(job?.status!=='complete')throw Error(job?.error||'Job timed out. It may still be running; inspect the runner.');report=job.report;artifactBase=runner+`/artifacts/jobs/${created.id}/`;$('#brief-text').textContent=report.description||description;syncBriefAndDims();await loadIteration(report.final_iteration);renderDashboard();$('#brief-feedback').textContent='Build complete. Measured results and downloads updated.';tab('preview');if(pendingDesign){const plist=loadDesigns();const pd=plist.find(x=>x.id===pendingDesign.id);if(pd){pd.revisions.push({n:pd.revisions.length+1,spec:{...spec},evaluated:true,passed:job.report.passed,source_job:created.id,note:'live CAD run',saved_at:nowIso()});pd.description=description;pd.updated_at=nowIso();if(persistDesigns(plist)){toast('Revision '+pd.revisions.length+' saved to "'+pd.name+'".');const m=$('#design-mode');if(m&&!m.hidden)m.querySelector('.design-mode-note').textContent='Attached to a live runner — rebuilds update this design.'}}}}catch(err){$('#brief-feedback').textContent=err.message}finally{jobBusy=false;$('#submit-brief').disabled=false}};
async function board(){const nets=await json('artifacts/board/nets.json');$('#schematic').innerHTML=`<svg viewBox="0 0 600 310" role="img" aria-label="Four parallel nets from J1 to J2"><g font-family="IBM Plex Mono,monospace" fill="#495d51"><rect x="50" y="50" width="90" height="200" rx="5" fill="#f5f1e5" stroke="#9fae98"/><rect x="460" y="50" width="90" height="200" rx="5" fill="#f5f1e5" stroke="#9fae98"/><text x="77" y="30" font-size="16">J1</text><text x="486" y="30" font-size="16">J2</text>${nets.nets.map((n,i)=>`<path d="M110 ${85+i*45}H490" stroke="${i===0?'#aa6b87':'#388b7f'}" stroke-width="2"/><circle cx="110" cy="${85+i*45}" r="5" fill="#f4efdf" stroke="#388b7f"/><circle cx="490" cy="${85+i*45}" r="5" fill="#f4efdf" stroke="#388b7f"/><text x="285" y="${75+i*45}" font-size="12">${escape(n.name)}</text><text x="78" y="${90+i*45}" font-size="12">${i+1}</text><text x="510" y="${90+i*45}" font-size="12">${i+1}</text>`).join('')}</g></svg>`;$('#board-svg').src='artifacts/board/board.svg';const drc=await json('artifacts/board/drc.json');$('#board-status').textContent=`KiCad ${drc.kicad_version} DRC: ${drc.violations.length} reported violations, ${drc.unconnected_items.length} unconnected items. ${drc.ignored_checks.length} checks ignored by the default rules. No schematic parity or electrical function verification.`}
try{init3D()}catch(e){$('#viewport').innerHTML='<p style="padding:240px 25px 0">WebGL is unavailable. Measurements and CAD downloads remain available.</p>';console.warn(e.message)}
try{report=await json(artifactBase+'report.json');reportReadyResolve(report);syncBriefAndDims();await loadIteration(report.final_iteration);renderDashboard();await board();tab((location.hash||'').replace(/^#\/?/,'')||'dashboard');pulseHero()}catch(e){reportReadyResolve(null);setViewStatus('Recorded geometry unavailable on this deployment — check the connection.','error');toast('Build artifacts unavailable: '+e.message);$('#activity').textContent='Could not load recorded evidence. Please refresh or inspect the source repository.'}
if(['127.0.0.1','localhost'].includes(location.hostname)&&location.port==='8766'){try{await json('/api/health');runner=location.origin;$('#connection-label').textContent='Local runner connected';$('#composer-mode').textContent='LOCAL CAD KERNEL';$('#footer-mode').textContent='LOCAL RUNNER · DETERMINISTIC CAD'}catch{}}
// ---- My designs: client-side library (localStorage only; no server, no account) ----
let storageOK=true,pendingDesign=null;
function nowIso(){return new Date().toISOString()}
function loadDesigns(){try{const raw=localStorage.getItem(DESIGNS_KEY);return raw?JSON.parse(raw):[]}catch{storageOK=false;return[]}}
function persistDesigns(list){try{localStorage.setItem(DESIGNS_KEY,JSON.stringify(list));storageOK=true;return true}catch{storageOK=false;return false}}
function currentSpec(){const s={};for(const name of ['length','width','mast_height'])s[name]=Number($('#'+name).value);return s}
function inTemplateRange(spec){return [['length',120,180],['width',80,110],['mast_height',35,75]].every(([k,min,max])=>Number.isFinite(spec[k])&&spec[k]>=min&&spec[k]<=max)}
function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,32)||'design'}
function downloadText(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
function designState(d){const last=d.revisions[d.revisions.length-1];if(last.evaluated)return last.passed?'EVALUATED · PASS':'EVALUATED · FAIL';return d.kind==='imported'?'IMPORTED · NOT EVALUATED':'LOCAL DRAFT'}
function designCard(d){
 const last=d.revisions[d.revisions.length-1],state=designState(d),rv=d.revisions.length;
 return `<article class="design-card"><div class="design-card-head"><span class="design-kind ${d.kind}">${d.kind.toUpperCase()}</span><span class="design-id mono">${rv} revision${rv>1?'s':''}</span></div><h3>${escape(d.name)}</h3><p class="design-desc">${escape(d.description||'No description yet.')}</p><div class="design-spec">${last.spec.length} × ${last.spec.width} mm · mast ${last.spec.mast_height} mm</div><div class="design-state ${last.evaluated?(last.passed?'pass':'fail'):''}">${state}</div><div class="design-actions"><button class="text-button" data-design="${d.id}" data-act="open">Open ↗</button><button class="text-button" data-design="${d.id}" data-act="export">Export ↓</button><button class="text-button" data-design="${d.id}" data-act="rev">Save revision</button><button class="text-button" data-design="${d.id}" data-act="delete">Delete</button></div></article>`;
}
function renderDesigns(){
 const list=loadDesigns();
 const count=$('#designs-count');if(count)count.textContent=storageOK?`${list.length} saved in this browser`:'storage unavailable — nothing will persist';
 const host=$('#designs');if(!host)return;
  const demoSpec={length:DEMO_SPEC.length,width:DEMO_SPEC.width,mast_height:DEMO_SPEC.mast_height};
  const demoDesc=report?.description||'The recorded example workspace.';
  const demo=`<article class="design-card"><div class="design-card-head"><span class="design-kind">EXAMPLE</span><span class="design-id mono">fixed · recorded build</span></div><h3>Rove–1</h3><p class="design-desc">${escape(demoDesc)}</p><div class="design-spec">${demoSpec.length} × ${demoSpec.width} mm · mast ${demoSpec.mast_height} mm</div><div class="design-state ${report?.passed?'pass':'fail'}">${report?.passed?'EVALUATED · PASS':'EVALUATED · FAIL'}</div><div class="design-actions"><button class="text-button" data-design="__demo" data-act="open">Open ↗</button><button class="text-button" data-design="__demo" data-act="export">Export ↓</button></div></article>`;
 host.innerHTML = (!storageOK)?`<div class="empty-designs">Browser storage is unavailable in this context (e.g. private mode). Designs cannot be saved here.</div>` : (list.length?list.map(designCard).join(''):`<div class="empty-designs">No saved designs yet. Import a design bundle or create one from the parametric template.</div>`)+demo;
}
function designBundle(d){return{format:'autocadent-design',version:1,name:d.name,description:d.description,spec:{...d.revisions[d.revisions.length-1].spec},kind:d.kind,source:d.source,created_at:d.created_at,updated_at:d.updated_at,revisions:d.revisions.map(r=>({n:r.n,spec:r.spec,evaluated:r.evaluated,passed:r.passed,source_job:r.source_job||null,note:r.note||'',saved_at:r.saved_at}))}}
function exportDesign(id){
  if(id==='__demo'){downloadText('rove-1-recorded.autocadent.json',JSON.stringify(designBundle({id:'__demo',name:'Rove-1 (recorded example)',description:report?.description||document.getElementById('brief-text')?.textContent||'Recorded Rove-1 build.',spec:{...DEMO_SPEC},kind:'example',source:'demo',created_at:nowIso(),updated_at:nowIso(),revisions:[{n:1,spec:{...DEMO_SPEC},evaluated:true,passed:!!report?.passed,source_job:null,note:'recorded build',saved_at:nowIso()}]}),null,2));toast('Recorded example exported as a design bundle.');return}
 const list=loadDesigns(),d=list.find(x=>x.id===id);if(!d)return;
 downloadText(slug(d.name)+'.autocadent.json',JSON.stringify(designBundle(d),null,2));toast('Exported "'+d.name+'" bundle.');
}
function openDesign(id){
model='rove1';syncModelButtons();
 if(id==='__demo'){pendingDesign=null;const m=$('#design-mode');if(m)m.hidden=true;$('#length').value=DEMO_SPEC.length;$('#width').value=DEMO_SPEC.width;$('#mast_height').value=DEMO_SPEC.mast_height;toast('Rove–1 recorded example loaded.');tab('preview');return}
 const list=loadDesigns(),d=list.find(x=>x.id===id);if(!d)return;
 pendingDesign=d;const last=d.revisions[d.revisions.length-1];
 $('#length').value=last.spec.length;$('#width').value=last.spec.width;$('#mast_height').value=last.spec.mast_height;$('#brief').value=d.description||'';
 const mode=$('#design-mode');mode.hidden=false;$('#design-mode-name').textContent=d.name;
 const note=mode.querySelector('.design-mode-note');
 note.textContent=last.evaluated?(last.source_job&&runner?'Attached to a live runner — rebuilds update this design.':'Evaluated earlier; rebuild via the local runner to refresh geometry.'):(d.kind==='imported'?'Imported locally — no CAD artifacts yet. Submit to build.' : 'Local draft — no CAD artifacts yet. Submit to build.');
 if(last.evaluated&&last.source_job&&runner){json(runner+'/api/jobs/'+last.source_job,{headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})}}).then(j=>{if(j?.status==='complete'){report=j.report;artifactBase=runner+`/artifacts/jobs/${last.source_job}/`;const bt=document.getElementById('brief-text');if(bt)bt.textContent=d.description||'';loadIteration(report.final_iteration).then(()=>{renderDashboard();renderEvidence&&renderEvidence()})}}).catch(()=>{})}
 toast('Design "'+d.name+'" loaded into the workspace.');tab('preview');
}
function saveRevision(id){
 const list=loadDesigns(),d=list.find(x=>x.id===id);if(!d)return;
 const spec=currentSpec();
 if(!inTemplateRange(spec)){toast('Dimensions must stay inside the template ranges to save a revision.');return}
 if(!$('#brief').value.trim()){toast('Add a short description first.');return}
 d.revisions.push({n:d.revisions.length+1,spec:{...spec},evaluated:false,passed:false,source_job:null,note:d.id===pendingDesign?.id?'current workspace draft':'local draft',saved_at:nowIso()});
 d.description=$('#brief').value.trim();d.updated_at=nowIso();
 if(persistDesigns(list)){renderDesigns();toast('Revision '+d.revisions.length+' saved locally for "'+d.name+'".')}else toast('Changes not saved — browser storage unavailable.');
}
let confirmId=null;
function deleteClick(id,btn){if(confirmId===id){confirmId=null;const list=loadDesigns(),d=list.find(x=>x.id===id);if(d){list.splice(list.indexOf(d),1);if(persistDesigns(list)){if(pendingDesign?.id===id){pendingDesign=null;$('#design-mode').hidden=true}renderDesigns();toast('Deleted "'+d.name+'".')}}}else{confirmId=id;btn.textContent='Confirm delete?';btn.classList.add('danger');setTimeout(()=>{if(confirmId===id){confirmId=null;renderDesigns()}},3500)}}
function importDesigns(text,fileName){
 let b;try{b=JSON.parse(text)}catch(e){throw new Error('Not valid JSON: '+e.message)}
 if(!b||typeof b!=='object'||Array.isArray(b))throw new Error('A design bundle must be a JSON object.');
 const spec={};for(const k of ['length','width','mast_height']){const v=Number(b.spec?.[k]);if(!Number.isFinite(v))throw new Error('Bundle needs numeric spec.'+k+'.');spec[k]=v}
 const norm=r=>({n:r.n||1,spec:{length:Number(r.spec?.length??spec.length)||spec.length,width:Number(r.spec?.width??spec.width)||spec.width,mast_height:Number(r.spec?.mast_height??spec.mast_height)||spec.mast_height},evaluated:!!r.evaluated,passed:!!r.passed,source_job:r.source_job?String(r.source_job):null,note:r.note?String(r.note).slice(0,120):'imported revision',saved_at:r.saved_at||nowIso()});
 const revisions=Array.isArray(b.revisions)&&b.revisions.length?b.revisions.map(norm):[{n:1,spec:{...spec},evaluated:!!(b.evaluated??b.passed!==undefined),passed:!!b.passed,source_job:null,note:'imported bundle',saved_at:nowIso()}];
 return{id:slug((b.name||fileName||'imported')+'-'+Math.random().toString(36).slice(2,7)),name:String(b.name||fileName.replace(/\.autocadent\.json$|\.json$/i,'')||'Imported design').slice(0,40),description:String(b.description||'').slice(0,1500),spec:{...spec},kind:'imported',source:'file',created_at:b.created_at||nowIso(),updated_at:nowIso(),revisions};
}
function createFromTemplate(){modal('Save your design locally.',`<div class="design-dialog"><label for="design-name">Design name</label><input id="design-name" type="text" maxlength="40" value="Rove-1 variation" autocomplete="off"><p class="muted">Stored in this browser only (localStorage). No account, no upload. Live CAD still needs the local runner; a draft saves without artifacts until you run it.</p><button id="do-save-design" class="dark-button">Save design ↗</button></div>`);$('#do-save-design').onclick=()=>{const n=$('#design-name').value.trim();if(!n){$('#design-name').focus();return}const spec=currentSpec();if(!inTemplateRange(spec)){toast('Dimensions must stay inside the template ranges.');$('#modal').close();return}$('#modal').close();const d={id:'t-'+Math.random().toString(36).slice(2,9),name:n.slice(0,40),description:$('#brief').value.trim(),spec:{...spec},kind:'template',source:'template',created_at:nowIso(),updated_at:nowIso(),revisions:[{n:1,spec:{...spec},evaluated:false,passed:false,source_job:null,note:'created from parametric template',saved_at:nowIso()}]};const list=loadDesigns();list.unshift(d);if(persistDesigns(list)){renderDesigns();openDesign(d.id);toast('New design "'+d.name+'" saved locally.')}else toast('Could not save — browser storage unavailable.')};$('#design-name').focus()}
$('#designs').addEventListener('click',e=>{const b=e.target.closest('button[data-act]');if(!b)return;const id=b.dataset.design,act=b.dataset.act;if(act==='open')openDesign(id);else if(act==='export')exportDesign(id);else if(act==='rev')saveRevision(id);else if(act==='delete')deleteClick(id,b)});
$('#design-import').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const d=importDesigns(reader.result,f.name);const list=loadDesigns();list.unshift(d);if(persistDesigns(list)){renderDesigns();openDesign(d.id);toast('Imported "'+d.name+'" ('+d.revisions.length+' revision'+(d.revisions.length>1?'s':'')+').')}else toast('Import failed — browser storage unavailable.')}catch(err){toast('Import rejected: '+err.message)}};reader.readAsText(f);e.target.value=''};
$('#design-new').onclick=createFromTemplate;
$('#design-save-rev').onclick=()=>{if(pendingDesign)saveRevision(pendingDesign.id)};
$('#design-export').onclick=()=>{if(pendingDesign)exportDesign(pendingDesign.id)};
$('#design-close').onclick=()=>{pendingDesign=null;$('#design-mode').hidden=true;toast('Design closed — workspace left as it was.')};
