import * as THREE from 'three';
import { OrbitControls } from './vendor/OrbitControls.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let report, iteration=1, artifactBase='artifacts/demo/', currentGroup='all', translucent=true, exploded=false, runner='', token='', execution='deterministic', jobBusy=false;
let scene, camera, renderer, controls, assembly, renderRunning=false;
function tick(){if(!renderer)return;controls.update();renderer.render(scene,camera);updateScale()}
function startRender(){if(!renderer||renderRunning)return;renderRunning=true;renderer.setAnimationLoop(tick)}
function stopRender(){if(!renderer)return;renderRunning=false;renderer.setAnimationLoop(null)}
// ---- boot intro (loading sequence; purely decorative, uses real recorded values for init lines) ----
const boot=document.getElementById('boot');
let bootDone=false,booting=false;
let reportReadyResolve;const reportReady=new Promise(r=>reportReadyResolve=r);
function finishBoot(){if(!boot||bootDone)return;bootDone=true;booting=false;document.querySelectorAll('body>*:not(#boot)').forEach(n=>n.removeAttribute('inert'));boot.style.transition='opacity .5s ease';boot.style.opacity='0';setTimeout(()=>boot.remove(),520)}
async function realBootLines(){const r=await Promise.race([reportReady,new Promise(s=>setTimeout(()=>s(null),1000))]);
 const manifest='report.json · benchmark.json · board/drc.json · board/nets.json';
 if(!r)return[`geometry cache ........ unavailable`,`recorded build ........ —`,manifest,`revision status ....... build artifacts missing`,`workspace ............. recorded view only`];
 const last=r.iterations.at(-1),ev=last.evaluation,pass=ev.checks.filter(c=>c.passed).length,total=ev.checks.length;
 return[`geometry cache ........ ${ev.checks[0].measured} valid solids`,`recorded build ........ ${r.seconds}s kernel workflow · ${r.iterations.length} iteration${r.iterations.length>1?'s':''}`,manifest,`revision status ....... REV ${String(r.final_iteration).padStart(2,'0')} · ${r.passed?'EVALUATED · PASS':'NEEDS REVIEW'} · ${pass}/${total} checks`,`workspace ............. dashboard ready`]}
if(boot){if(matchMedia('(prefers-reduced-motion: reduce)').matches){boot.remove()}else{booting=true;document.querySelectorAll('body>*:not(#boot)').forEach(n=>n.setAttribute('inert',''));const guard=setTimeout(finishBoot,3400);boot.addEventListener('click',finishBoot);window.addEventListener('keydown',e=>{if(!bootDone&&['Enter','Space','Escape'].includes(e.code)&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))finishBoot()});setTimeout(async()=>{if(bootDone)return;boot.dataset.phase='term';const lines=await realBootLines();boot.querySelector('.boot-term-lines').innerHTML='';lines.forEach((t,i)=>{const d=document.createElement('div');d.className='boot-line';d.innerHTML=`<span>${t}</span><i></i>`;boot.querySelector('.boot-term-lines').appendChild(d);setTimeout(()=>{if(!bootDone)d.classList.add('on')},i*140)});setTimeout(finishBoot,300+lines.length*140+120)},1400)}}
const toast=s=>{ $('#toast').textContent=s; $('#toast').classList.add('show'); setTimeout(()=>$('#toast').classList.remove('show'),4000); };
async function json(url,options){const r=await fetch(url,options); if(!r.ok){let detail;try{detail=(await r.json()).detail}catch{}throw Error(detail?JSON.stringify(detail):`Request failed (${r.status})`)}return r.json()}
function modal(title,html){$('#modal-content').innerHTML=`<h2>${title}</h2>${html}`; if(!$('#modal').open)$('#modal').showModal()}
$('#close-modal').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close()};
function init3D(){
 scene=new THREE.Scene(); camera=new THREE.PerspectiveCamera(33,1,.1,3000); camera.up.set(0,0,1);
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;
 $('#viewport').appendChild(renderer.domElement); controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=150;controls.maxDistance=850;controls.maxPolarAngle=Math.PI*.85;
 scene.add(new THREE.HemisphereLight(0xfff9e8,0x596c65,2.4)); const sun=new THREE.DirectionalLight(0xfff7e4,3.5);sun.position.set(150,-180,260);scene.add(sun);const fill=new THREE.DirectionalLight(0x8ac0bb,1.2);fill.position.set(-100,150,60);scene.add(fill);
 const grid=new THREE.GridHelper(550,22,0xb8b7a3,0xd4d2bf);grid.rotation.x=Math.PI/2;grid.position.z=-25;grid.material.transparent=true;grid.material.opacity=.4;scene.add(grid);
 const ring=new THREE.Mesh(new THREE.RingGeometry(119,119.35,100),new THREE.MeshBasicMaterial({color:0xa5b2a1,transparent:true,opacity:.5,side:THREE.DoubleSide}));ring.position.z=-24.8;scene.add(ring);
 new ResizeObserver(()=>{let w=$('#viewport').clientWidth,h=$('#viewport').clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}).observe($('#viewport'));
 reset();if(!$('#preview-view').hidden)startRender();
}
function reset(){if(!camera)return;camera.position.set(265,-330,225);controls.target.set(0,0,20);controls.update()}
let lastScale='';
function updateScale(){
 if(!camera||!renderer)return;const vw=$('#viewport'),bar=$('#scale-bar');if(!vw||!bar||!vw.clientWidth)return;
 const halfW=vw.clientWidth/2,halfH=vw.clientHeight/2,plane=new THREE.Plane(new THREE.Vector3(0,0,1),25);
 const hit=(x,y)=>{const ndc=new THREE.Vector2(x/halfW-1,-(y/halfH-1));const r=new THREE.Raycaster();r.setFromCamera(ndc,camera);const p=new THREE.Vector3();return r.ray.intersectPlane(plane,p)?p:null};
 const a=hit(halfW,halfH),b=hit(halfW+140,halfH);if(!a||!b)return;const dist=a.distanceTo(b);if(dist<1e-6)return;
 const nice=[500,200,100,50,20,10];const m=nice.find(v=>v<=dist)||10;const key=`${m} mm ${(140*m/dist).toFixed(0)}`;
 if(key===lastScale)return;lastScale=key;bar.style.width=(140*m/dist).toFixed(0)+'px';$('#scale-label').textContent=`${m} mm`;
}
function drawMeshes(meshes){
 if(!scene)return;
 if(assembly){assembly.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose()});scene.remove(assembly)}
 assembly=new THREE.Group();
 for(const p of meshes){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(p.vertices.flat(),3));geometry.setIndex(p.triangles.flat());geometry.computeVertexNormals();
 const material=new THREE.MeshStandardMaterial({color:p.color,roughness:.58,metalness:.12,transparent:true,opacity:translucent?.58:1,side:THREE.DoubleSide,depthWrite:!translucent});
 const mesh=new THREE.Mesh(geometry,material);mesh.userData=p;const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geometry,25),new THREE.LineBasicMaterial({color:p.group==='electronics'?0x286f70:0x536059,transparent:true,opacity:.5}));mesh.add(edges);assembly.add(mesh)}
 updateModel();
}
function updateModel(){if(!assembly)return;assembly.children.forEach((mesh,i)=>{mesh.visible=currentGroup==='all'||mesh.userData.group===currentGroup;mesh.material.opacity=translucent?.56:1;mesh.material.depthWrite=!translucent;mesh.position.z=exploded?(mesh.userData.group==='electronics'?48:mesh.userData.name==='Sensor mast'?30:mesh.userData.name==='Board tray'?20:0):0; if(mesh.userData.group==='mobility')mesh.position.y=exploded?(i%4<2?-22:22):0;});}
$$('[data-group]').forEach(b=>b.onclick=()=>{currentGroup=b.dataset.group;$$('[data-group]').forEach(el=>el.classList.toggle('active',el===b));updateModel()});
$('#reset-view').onclick=reset;$('#wireframe').onclick=()=>{translucent=!translucent;$('#wireframe').setAttribute('aria-pressed',translucent);updateModel()};$('#explode').onclick=()=>{exploded=!exploded;$('#explode').setAttribute('aria-pressed',exploded);updateModel()};
function zoom(f){camera.position.sub(controls.target).multiplyScalar(f).add(controls.target);controls.update()};$('#zoom-in').onclick=()=>zoom(.85);$('#zoom-out').onclick=()=>zoom(1.15);
function tab(name){$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);if(b.dataset.tab===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});['dashboard','preview','files','schematic','layout'].forEach(n=>$(`#${n}-view`).hidden=n!==name);if(name==='preview'){window.dispatchEvent(new Event('resize'));startRender()}else stopRender();const names={dashboard:'Dashboard',preview:'Explorer',files:'Files',schematic:'Schematic',layout:'Layout'};const crumb=$('#view-crumb');if(crumb)crumb.textContent=names[name];}
$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function renderEvidence(){
 const item=report.iterations[iteration-1], first=report.iterations[0], last=report.iterations.at(-1);
 const failed=first.evaluation.checks.filter(c=>!c.passed);
 const isRecorded=report.execution!=='ao-worker'&&!runner;
 $('#activity').innerHTML=`<div class="event"><h3>Specification accepted</h3><p>${item.spec.length} × ${item.spec.width} mm platform. 60 × 40 mm board. Fixed rover template.</p></div><div class="event ${failed.length?'failure':''}"><h3>Geometry built & evaluated</h3><p>${first.evaluation.checks[0].measured} valid solids. ${failed.length?`${failed.length} dimensional constraints failed.`:'All scoped checks passed on the first build.'}</p>${failed.length?`<span class="event-tag">${failed.map(c=>escape(c.name)).join(' · ')}</span>`:''}</div>${report.iterations.length>1?`<div class="event"><h3>Repair policy applied</h3><p>Thickness → ${last.spec.thickness} mm<br>Tray walls → ${last.spec.wall} mm<br>Board gap → ${last.spec.clearance} mm</p></div>`:''}<div class="event"><h3>${report.passed?'Build passes scoped checks':'Build needs review'}</h3><p>${last.evaluation.checks.filter(c=>c.passed).length} / ${last.evaluation.checks.length} measured checks · ${report.seconds}s kernel workflow</p><span class="event-tag pass">${report.passed?'ARTIFACTS READY':'REVIEW REPORT'}</span></div>`;
 $('#checks').innerHTML=item.evaluation.checks.filter(c=>['Chassis thickness','Tray wall','Board clearance'].includes(c.name)).map(c=>`<article class="check ${c.passed?'':'fail'}"><div><span>${escape(c.name)}</span><b>${c.passed?'✓ PASS':'! FAIL'}</b></div><p>${c.measured.toFixed(1)} <small>mm</small></p><span>REQUIRED ${escape(c.requirement)}</span></article>`).join('');
 $('#revision-label').textContent=`REV ${String(iteration).padStart(2,'0')} · ${item.evaluation.passed?'EVALUATED':'CONSTRAINT FAILURE'}`;
 $('#iteration-summary').textContent=`Iteration ${iteration} of ${report.iterations.length} · ${item.evaluation.checks[0].passed?'Valid solids':'Invalid geometry'} ≠ dimensional acceptance`;
 $('#project-state').textContent=report.passed?'Evaluated exemplar':'Needs review';
 $('#replay-btn').textContent=iteration===1&&report.iterations.length>1?'↗ Inspect repaired build':'↺ Inspect initial build';
 $('#run-label').textContent=report.execution==='ao-worker'?'AO WORKER RESULT':runner?'LOCAL KERNEL RESULT':'RECORDED RUN';
 renderFiles();
}
async function loadIteration(n){iteration=n;renderEvidence();try{drawMeshes(await json(`${artifactBase}iteration-${iteration}/mesh.json`))}catch(e){toast('Geometry could not load: '+e.message)}}
$('#replay-btn').onclick=()=>loadIteration(iteration===1?report.iterations.length:1);
const files=()=>[
 ['ZIP','rove-1-cad.zip','Complete CAD bundle · source, STEP, printable STL + report',`${artifactBase}rove-1-cad.zip`],
 ['STEP','rove-1.step','Editable assembly · wheels and sensors are envelopes',`${artifactBase}final/rove-1.step`],
 ['STL','chassis.stl','Printable chassis · repaired revision',`${artifactBase}final/chassis.stl`],
 ['STL','board-tray.stl','Board tray · measured wall and clearance',`${artifactBase}final/board-tray.stl`],
 ['STL','sensor-mast.stl','Sensor support · template geometry',`${artifactBase}final/sensor-mast.stl`],
 ['PCB','rove-1-board.zip','KiCad board, Gerbers, drill, BOM, net data + DRC · fixed exemplar','artifacts/board/rove-1-board.zip'],
 ['JSON','report.json','Every iteration, constraint and artifact hash',`${artifactBase}report.json`]
];
function fileRows(){return files().map(([ext,name,desc,url])=>`<div class="file-row"><span>${ext}</span><div><b>${name}</b><small>${desc}</small></div><a href="${escape(url)}" download aria-label="Download ${name}">↓</a></div>`).join('')}
function renderFiles(){$('#file-list').innerHTML=fileRows()}
function renderDashboard(){
  const last=report.iterations.at(-1), keyChecks=last.evaluation.checks.filter(c=>['Chassis thickness','Tray wall','Board clearance'].includes(c.name));
  const nav=(id,label,note)=>`<button class="dash-nav" data-goto="${id}"><b>${label}</b><span>${escape(note)}</span>↗</button>`;
  $('#dashboard').innerHTML=`<div class="view-heading"><span class="eyebrow">WORKSPACE DASHBOARD</span><h2>Rove–1, at a glance.</h2><p>Revision status, measured checks and the repair benchmark for the recorded build. Jump into any view from here.</p></div>
  <div class="dash-grid">
    <article class="dash-card"><span class="eyebrow">REVISION STATUS</span><div class="revision-big">REV ${String(report.final_iteration).padStart(2,'0')}</div><div class="revision-state ${report.passed?'':'fail'}">${report.passed?'EVALUATED · PASS':'NEEDS REVIEW'}</div><p>${report.iterations.length} iteration${report.iterations.length>1?'s':''} · ${report.seconds}s kernel workflow</p><p class="muted">${report.passed?'All scoped dimensional checks pass on the repaired build.':'One or more scoped checks still fail on the final revision.'}</p></article>
    <article class="dash-card"><span class="eyebrow">CHECKS SUMMARY</span>${keyChecks.map(c=>`<div class="dash-check ${c.passed?'':'fail'}"><span>${escape(c.name)}</span><b>${c.measured.toFixed(1)} <small>mm</small></b><em>${c.passed?'PASS':'FAIL'}</em></div>`).join('')}<p class="muted">18 valid solids · measured on solid geometry, not a print or stress test.</p></article>
    <article class="dash-card"><span class="eyebrow">REPAIR BENCHMARK</span><div class="bench-big" id="bench-figure">…</div><p class="muted" id="bench-note">Loading regression corpus…</p></article>
  </div>
  <div class="dash-links">${nav('preview','Assembly explorer','orbit · isolate · explode')}${nav('files','Build outputs','STEP · STL · ZIP · source + hashes')}${nav('schematic','Connectivity diagram','four nets · J1 ↔ J2')}${nav('layout','Board layout','KiCad export · DRC evidence')}</div>`;
  $$('[data-goto]').forEach(b=>b.onclick=()=>tab(b.dataset.goto));
  json('artifacts/benchmark.json').then(b=>{$('#bench-figure').innerHTML=`<b>${b.after_pass_count}</b>/${b.case_count}<span>pass after repair</span>`;$('#bench-note').textContent=`${b.before_pass_count} of ${b.case_count} initially accepted; deterministic repair recovers ${b.after_pass_count-b.before_pass_count}. Fixed regression corpus, not an LLM benchmark.`}).catch(()=>{$('#bench-figure').textContent='—';$('#bench-note').textContent='Benchmark artifact unavailable.'});
};$('#export-btn').onclick=()=>modal('Take the build with you.',`<p>Final evaluated CAD plus a fixed connector-board exemplar. Sensor and wheel envelopes are included in STEP for assembly context, not as printable hardware.</p>${fileRows()}`);
$('#report-btn').onclick=()=>{const ev=report.iterations[iteration-1].evaluation;modal(`Revision ${iteration}: the evidence.`,`<p>Measured by OpenCASCADE. Solid validity is separate from dimensional acceptance. These checks do not certify strength, electrical safety, or printability.</p><table><thead><tr><th>Check</th><th>Measured</th><th>Requirement</th><th>Result</th></tr></thead><tbody>${ev.checks.map(c=>`<tr><td title="${escape(c.method)}">${c.name}</td><td>${c.measured} ${c.unit}</td><td>${escape(c.requirement)}</td><td>${c.passed?'PASS':'FAIL'}</td></tr>`).join('')}</tbody></table><p>Tray wall: paired planar side-face offsets. Board gap: minimum solid distance to tray sidewalls. No global wall analysis or structural simulation.</p><a class="download-link" href="${artifactBase}report.json" download>Download complete report ↗</a>`)};
$('#benchmark-btn').onclick=async()=>{try{const b=await json('artifacts/benchmark.json');modal('Small corpus. Real measurements.',`<p>${escape(b.kind)}. Each case builds real solids, evaluates, applies a fixed repair policy, then evaluates again.</p><table><thead><tr><th>Case</th><th>Initial</th><th>After repair</th></tr></thead><tbody>${b.cases.map(c=>`<tr><td>${c.case}</td><td>${c.before.passed?'PASS':'FAIL'}</td><td>${c.after.passed?'PASS':'FAIL'}</td></tr>`).join('')}</tbody></table><p>${b.before_pass_count} of ${b.case_count} initially accepted; ${b.after_pass_count} of ${b.case_count} after repair. This is a fixed regression corpus, not a general agent benchmark.</p><a class="download-link" href="artifacts/benchmark.json" download>Download benchmark artifact ↗</a>`)}catch(e){toast(e.message)}};
$('#guide-btn').onclick=()=>modal('An open engineering notebook.',`<p>AutoCadent turns a bounded robot brief into geometry you can inspect, evaluate and take with you.</p><h3>01 / Inspect the assembly</h3><p>Orbit the actual tessellated CAD model. Isolate the chassis, board or wheels. Toggle X-ray or explode the assembly.</p><h3>02 / Follow the correction</h3><p>Inspect the initial build: valid solids with failed thickness, wall and clearance constraints. Switch to the repaired build and open its measurements.</p><h3>03 / Build your variation</h3><p>Start the local runner, connect, edit the dimensions and submit your brief. The deterministic mode uses explicit dimensions; your prose is preserved as design intent. AO mode dispatches a real AO worker with the same bounded template.</p><pre>uv sync --python 3.12\nuv run uvicorn autocadent.api:app --host 127.0.0.1 --port 8766\n# Open http://127.0.0.1:8766</pre><p>GitHub Pages serves recorded artifacts. It cannot run CAD or agents. The signal board is a fixed exemplar, not a motor controller. The rover is an educational assembly, not validated hardware.</p><a class="download-link" target="_blank" rel="noreferrer" href="https://github.com/Anthony-Sin/AutoCadent-SyndicatebyMaximor">Setup, architecture & demo guide ↗</a>`);
$('#mcp-btn').onclick=async()=>{try{const e=await json('artifacts/mcp-status.json');modal('Tools, actually connected.',`<p>MCP initialize, tools/list and useful-call evidence from the local toolchain. These are recorded verification results, not a current connection to your machine.</p><table><tr><th>Server</th><th>Tools</th><th>Verified call</th></tr>${e.servers.map(s=>`<tr><td>${escape(s.name)}</td><td>${s.tools}</td><td>${escape(s.call)} · ${s.passed?'PASS':'FAIL'}</td></tr>`).join('')}</table><p>KiCad uses the pinned BCI-style uvx setup. AutoCadent CAD is a project-specific MCP server for bounded CadQuery generation and measurement.</p><a class="download-link" href="artifacts/mcp-status.json" download>Download verification summary ↗</a>`)}catch(e){toast(e.message)}};
function connectDialog(){modal('Bring your own runner.',`<p>Pages is a recorded artifact explorer. Start the runner locally and open its address for live CAD. Connecting from Pages requires an explicitly allowed origin. Use an authenticated HTTPS runner for remote hosting.</p><label for="runner-url">Runner URL</label><input id="runner-url" type="url" value="${escape(runner||'http://127.0.0.1:8766')}" placeholder="http://127.0.0.1:8766"><label for="runner-token">Runner token (only if configured; kept in memory)</label><input id="runner-token" type="password" autocomplete="off"><label for="execution-mode">Execution mode</label><select id="execution-mode"><option value="deterministic">Local CAD kernel + deterministic repair policy</option><option value="ao">Supervisor → actual AO worker → evaluator</option></select><button id="do-connect" class="dark-button">Connect runner ↗</button><p id="connect-status" role="status"></p>`);$('#execution-mode').value=execution;$('#do-connect').onclick=async()=>{const raw=$('#runner-url').value;try{const url=new URL(raw);if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.search||url.hash)throw Error('Use an HTTP(S) runner origin without credentials or query parameters.'); const next=url.origin; const nextToken=$('#runner-token').value; const mode=$('#execution-mode').value;const h=await json(next+'/api/health',{headers:nextToken?{Authorization:'Bearer '+nextToken}:{}});if(mode==='ao'&&!h.ao_enabled)throw Error('AO dispatch is disabled on this runner. Enable AUTOCADENT_ENABLE_AO=1 server-side.');runner=next;token=nextToken;execution=mode;$('#connection-label').textContent=mode==='ao'?'AO runner connected':'Local runner connected';$('#composer-mode').textContent=mode==='ao'?'AO WORKER DISPATCH':'LOCAL CAD KERNEL';$('#footer-mode').textContent=mode==='ao'?'RUNNER CONNECTED · AO JOBS ON REQUEST':'RUNNER CONNECTED · DETERMINISTIC CAD';$('#modal').close();toast('Runner connected. Edit dimensions and submit your brief.')}catch(e){$('#connect-status').textContent=e.message}};}
$('#connect-btn').onclick=connectDialog;
$('#brief-form').onsubmit=async e=>{e.preventDefault();if(jobBusy)return;if(!runner){$('#brief-feedback').textContent='Connect a local runner to generate your design. The recorded build is ready to inspect and download.';connectDialog();return}const description=$('#brief').value.trim();if(!description){$('#brief-feedback').textContent='Add a short description of your rover.';return}const spec={};for(const name of ['length','width','mast_height']){const input=$('#'+name);if(!input.checkValidity()){input.reportValidity();return}spec[name]=Number(input.value)}jobBusy=true;$('#submit-brief').disabled=true;$('#brief-feedback').textContent=execution==='ao'?'Supervisor dispatching an actual AO worker…':'Building and evaluating real CAD geometry…';const headers={'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};try{const created=await json(runner+'/api/jobs',{method:'POST',headers,body:JSON.stringify({description,spec,execution})});let job;const deadline=Date.now()+15*60*1000;while(Date.now()<deadline){job=await json(runner+'/api/jobs/'+created.id,{headers});if(job.status==='complete'||job.status==='failed')break;$('#brief-feedback').textContent=job.message||'CAD worker running…';await new Promise(r=>setTimeout(r,2000))}if(job?.status!=='complete')throw Error(job?.error||'Job timed out. It may still be running; inspect the runner.');report=job.report;artifactBase=runner+`/artifacts/jobs/${created.id}/`;$('#brief-text').textContent=description;await loadIteration(report.final_iteration);renderDashboard();$('#brief-feedback').textContent='Build complete. Measured results and downloads updated.';tab('preview')}catch(err){$('#brief-feedback').textContent=err.message}finally{jobBusy=false;$('#submit-brief').disabled=false}};
async function board(){const nets=await json('artifacts/board/nets.json');$('#schematic').innerHTML=`<svg viewBox="0 0 600 310" role="img" aria-label="Four parallel nets from J1 to J2"><g font-family="IBM Plex Mono,monospace" fill="#495d51"><rect x="50" y="50" width="90" height="200" rx="5" fill="#f5f1e5" stroke="#9fae98"/><rect x="460" y="50" width="90" height="200" rx="5" fill="#f5f1e5" stroke="#9fae98"/><text x="77" y="30" font-size="16">J1</text><text x="486" y="30" font-size="16">J2</text>${nets.nets.map((n,i)=>`<path d="M110 ${85+i*45}H490" stroke="${i===0?'#aa6b87':'#388b7f'}" stroke-width="2"/><circle cx="110" cy="${85+i*45}" r="5" fill="#f4efdf" stroke="#388b7f"/><circle cx="490" cy="${85+i*45}" r="5" fill="#f4efdf" stroke="#388b7f"/><text x="285" y="${75+i*45}" font-size="12">${escape(n.name)}</text><text x="78" y="${90+i*45}" font-size="12">${i+1}</text><text x="510" y="${90+i*45}" font-size="12">${i+1}</text>`).join('')}</g></svg>`;$('#board-svg').src='artifacts/board/board.svg';const drc=await json('artifacts/board/drc.json');$('#board-status').textContent=`KiCad ${drc.kicad_version} DRC: ${drc.violations.length} reported violations, ${drc.unconnected_items.length} unconnected items. ${drc.ignored_checks.length} checks ignored by the default rules. No schematic parity or electrical function verification.`}
try{init3D()}catch(e){$('#viewport').innerHTML='<p style="padding:240px 25px 0">WebGL is unavailable. Measurements and CAD downloads remain available.</p>';console.warn(e.message)}
try{report=await json(artifactBase+'report.json');reportReadyResolve(report);await loadIteration(report.final_iteration);renderDashboard();await board()}catch(e){reportReadyResolve(null);toast('Build artifacts unavailable: '+e.message);$('#activity').textContent='Could not load recorded evidence. Please refresh or inspect the source repository.'}
if(['127.0.0.1','localhost'].includes(location.hostname)&&location.port==='8766'){try{await json('/api/health');runner=location.origin;$('#connection-label').textContent='Local runner connected';$('#composer-mode').textContent='LOCAL CAD KERNEL';$('#footer-mode').textContent='LOCAL RUNNER · DETERMINISTIC CAD'}catch{}}
